framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
            outbox.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
            async:
                dsn: '%env(ASYNC_MESSENGER_TRANSPORT_DSN)%'
                serializer: Neuron\BuildingBlocks\Integration\IntegrationEventSerializer
                options:
                    exchange:
                        name: integration_events
                        type: topic
                    queues:
                        notifications:
                            binding_keys:
                                - notifications
                        gateway:
                            binding_keys:
                                - gateway
            sync: 'sync://'
            outbox:
                dsn: '%env(OUTBOX_TRANSPORT_DSN)%'
                options:
                    table_name: outbox_messages
                    auto_setup: false

        routing:
            App\BuildingBlocks\Domain\DomainEventInterface: sync
            App\Application\Contract\CommandInterface: sync
            App\Application\Contract\QueryInterface: sync
            App\BuildingBlocks\Application\Event\DomainEventNotificationInterface: outbox
            Neuron\BuildingBlocks\Integration\SentIntegrationEventInterface: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
